minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.87
neo_version_range=[26.1.2.87,26.2)
java_version=25
source_line=main
ffapi_version=
sgui_version=2.0.0+26.1
placeholder_version=3.0.0+26.1
common_protection_api_version=2.0.0
